EasyShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls',namespace='app')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from app import views
from app.forms import loginform,passwordchangeform,passwordresetform,setpasswordform
app_name = "app"
urlpatterns = [
    path('', views.home),
    #path('buyer/',views.buyer,name='buyer'),
    path('buyers/',views.buyers.as_view(),name='buyers'),
    path('seller/',views.seller,name='seller'),
    path('product-detail/<int:pk>', views.product_detail.as_view(), name='product-detail'),
    path('add-to-cart/',views.add_to_cart,name='add-to-cart'),
    path('cart/', views.show_cart, name='showcart'),
    path('pluscart/', views.plus_cart, name='pluscart'),
    path('minuscart/', views.minus_cart, name='minuscart'),
    path('removecart/', views.remove_cart, name='removecart'),
    
    path('buy/', views.buy_now, name='buy-now'),
    #path('profile/', views.profile, name='profile'),
    path('profile/', views.profileview.as_view(), name='profile'),
    
    path('address/', views.addres.as_view(), name='address'),
    path('orders/', views.orders, name='orders'),
    #path('changepassword/', views.change_password, name='changepassword'),
    path('mobile/', views.mobile, name='mobile'),
    #path('login/', views.login, name='login'),
    path('accounts/login/',auth_views.LoginView.as_view(template_name='app/login.html',authentication_form=loginform),name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/accounts/login/'),name='logout'),
    #path('registration/', views.customerregistration, name='customerregistration'),
    path('registration/',views.CustomerRegistrationView.as_view(),name='customerregistration'),
    path('checkout/', views.checkout, name='checkout'),
    path('paymentdone/', views.payment_done, name='paymentdone'),
    path('passwordchange/',auth_views.PasswordChangeView.as_view(template_name='passwordchange.html',form_class=passwordchangeform,success_url='/passwordchangedone/'),name='passwordchange'),
    path('passwordchangedone/',auth_views.PasswordChangeDoneView.as_view(template_name='app/passwordchangedone.html'),name='passwordchangedone'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='app/password_reset.html',form_class=passwordresetform,success_url='/password-reset-confirm/'),name='password_reset'),
    path('password-reset-confirm/',auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'),name='password-reset-confirm'),
    #path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'),name='password-reset-complete'),
    #path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html',form_class=setpasswordform),name='password_reset_confirm'),
    




]

app/templates/app/addtocart.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <h1 class="text-center mb-5">Shopping Cart</h1>
  <div class="col-sm-8">
  <div class="card">
   <div class="card-body">
    <h3>Cart</h3>
    {% for cart in carts %}
    <div class="row">
     <div class="col-sm-3 text-center align-self-center"><img src=" {{cart.product.image.url}} " alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"> </div>
     <div class="col-sm-9">
      <div>
       <h5>{{cart.product.title}}</h5>
       <p class="mb-2 text-muted small">{{cart.product.description}}</p>
       <div class="my-3">
        <label for="quantity">Quantity:</label>
        <a class="minus-cart btn" pid="{{cart.product.id}}"><i class="fas fa-minus-square fa-lg"></i></a>
          <span id="quantity">{{cart.quantity}}}</span>
        <a class="plus-cart btn" pid="{{cart.product.id}}"><i class="fas fa-plus-square fa-lg"></i></a>
       </div> 
       <div class="d-flex justify-content-between">
        <a href="#" class="btn btn-sm btn-secondary mr-3 remove-cart" pid="{{cart.product.id}}">Remove item </a>
        <p class="mb-0"><span><strong>Rs. {{cart.product.discount_price}}</strong></span></p>
       </div>
      </div>
     </div>
    </div>
    <hr class="text-muted">
    {% endfor %}
    
   </div>
   </div>
  </div>

  <div class="col-sm-4">
   <div class="card">
    <div class="card-body">
      <h3>The Total Amount of</h3>
      <ul class="list-group">
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">Amount<span>Rs. <span id="amount">{{amount}}</span></span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center px-0">Shipping<span>Rs. 70.00</span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
           <strong>Total</strong> <small>(including GST)</small>
         </div>
         <span><strong>Rs.<strong id="total_amount">{{total_amount}}</strong></strong></span>
       </li>
      </ul>
      <div class="d-grid"><a href="{% url 'app:checkout' %}" class="btn btn-primary">Place Order</a></div>
    </div>
   </div>
  </div>
  
 </div>
</div>
<div class="container">
 <div class="row">
  <div class="col-sm-8">
   <div class="card">
    <div class="card-body">
      <h5 class="mb-4">We accept</h5>
      <img src="{% static 'app/images/payment.png' %}" alt="" class="img-fluid">
    </div>
  </div>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!--Owl Carousel CSS-->
    <link rel="stylesheet" href="{% static 'app/css/owl.carousel.min.css' %}">

    <!--FontAwesome CSS-->
    <link rel="stylesheet" href="{% static 'app/css/all.min.css' %}">

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">


    <title>EasyShop {% block title %} {% endblock title %} </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
     <div class="container">
       <a class="navbar-brand" href="/">EasyShop</a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item">
             <a class="nav-link active" aria-current="page" href="/buyers">Home</a>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle text-white" href="#" id="electronicsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               Electronics
             </a>
             <ul class="dropdown-menu" aria-labelledby="electronicsDropdown">
               <li><a class="dropdown-item" href="{% url 'app:mobile' %}">Mobile</a></li>
               <li><a class="dropdown-item" href="#">Laptop</a></li>
             </ul>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle text-white" href="#" id="fashionDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               Fashion
             </a>
             <ul class="dropdown-menu" aria-labelledby="fashionDropdown">
               <li><a class="dropdown-item" href="#">Top Wear</a></li>
               <li><a class="dropdown-item" href="#">Bottom Wear</a></li>
             </ul>
           </li>
         </ul>
         <h4 style=" text-color:red">This is world's best shopping place</h4>
         <div>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
           <li class="nav-item dropdown mx-2">
              <a class="nav-link dropdown-toggle text-white" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <span class="text-capitalize">{{request.user}}</span>
              </a>
              <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                <li><a class="dropdown-item" href="{% url 'app:profile' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'app:orders' %}">Orders</a></li>
                <li><a class="dropdown-item" href="{% url 'app:passwordchange' %}">Change Password</a></li>
                <li><a class="dropdown-item" href="{% url 'app:logout' %}">Logout</a></li>
              </ul>
            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'app:showcart' %}" class="nav-link text-white"><span class="badge bg-danger">{{total}}</span> Cart </a>
            </li>
            {% else %}
            <li class="nav-item mx-2">
             <a href="{% url 'app:login' %}" class="nav-link text-white">Login</a>
            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'app:customerregistration' %}" class="nav-link text-white">Registration</a>
            </li>
            {% endif %}
          </ul>
         </div>
       </div>
     </div>
    </nav>
    {% block banner_slider %} {% endblock banner_slider %}
    {% block livesale %} {% endblock livesale %}
    {% block main-content %} {% endblock main-content %}
    {% block payment %} {% endblock payment %}
    <!-- Start Footer -->
    <footer class="container-fluid bg-dark text-center p-2 mt-5">
        <small class="text-white">Copyright &copy; 2021 || Designed By HarshKumarChoudhary || </small>
        <img src="{% static 'app/images/payment.png' %}" alt="" srcset="" class="img-fluid" height="2px">
    </footer> <!-- End Footer -->

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <script src="{% static 'app/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'app/js/all.min.js' %}"></script>
    <script src="{% static 'app/js/myscript.js' %}"></script>
  </body>
</html>

app/templates/app/buynow.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
Product Buy Now
{% endblock main-content %}

app/templates/app/changepassword.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
 <h3>Welcome {{request.user}}</h3>
  <div class="col-sm-2 border-end">
   <ul class="list-unstyled">
    <li class="d-grid"><a href="{% url 'app:profile' %}" class="btn btn-primary">Change Password</a></li>
   </ul>
  </div>
  <div class="col-sm-9 offset-sm-1">
   <form>
     <div class="mb-3">
       <label for="exampleInputEmail1" class="form-label">Email address</label>
       <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
     </div>
     <div class="mb-3">
       <label for="exampleInputPassword1" class="form-label">New Password</label>
       <input type="password" class="form-control" id="exampleInputPassword1">
     </div>
     <div class="mb-3">
       <label for="exampleInputPassword1" class="form-label">Confirm New Password</label>
       <input type="password" class="form-control" id="exampleInputPassword1">
     </div>
     <button type="submit" class="btn btn-primary">Submit</button>
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/customerregistration.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Customer Registration{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Customer Registration</h3>
   <hr>

   <form action="" method="post" novalidate class="shadow p-5">
   {% if messages %}
      {% for message in messages %}
      <p {% if message.tags %}class ="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
      {% endfor %}
   {% endif %}
    {% csrf_token %}
    {% for f in form %}
      <div class="form-group mb-3">
      {{f.label_tag}}{{f}}<small class="text-danger">{{f.errors|striptags}}</small>
      </div>
    {% endfor %}
    <input type="submit" value="Submit" class="btn btn-primary">
    <br>
    <div class="text-center text-primary fw-bold"><small>Existing User ?<a href = {% url 'app:login' %} class="text-danger"> Login Now </a></small></div>
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <p class = "alert alert-danger my-3">{{error}}</p>
    {% endfor %}
    {% endif %}
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/emptycart.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Empty Cart{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <h3 class="text-center ">You have no product in the cart</h3>
  <div class="text-center">
  <img src="{% static 'app/images/emptycart.png' %}" alt="" ckass="img-fluid img-thumbnail w-25">
  </div>
  </div>
  </div>
  
    
{% endblock main-content %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Login</h3>
   <br>
   <form action="" method="post" novalidate class="shadow p-5">
    {% csrf_token %}
    {% for f in form %}
    <div class="form-group">
    {{f.label_tag}}{{f}}<small class="text-danger">{{f.errors|striptags}}</small><br>
    </div>
    {% endfor %}
    <small><a href="{% url 'app:password_reset' %}">Forot Password?</a></small><br>
    <input type="submit" class="btn btn-primary mt-4" value="Login">
    <br>
    <div class="text-center text-primary fw-bold"><small> New to EasyShop ? <a href="{% url 'app:customerregistration' %}" class="text-danger">Create an Account</a></small></div>
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
    {% endfor %}
    {% endif %}
    </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/mobile.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <div class="col-sm-3">
   These are the list of mobiles:
  </div>
  <div class="col-sm-8 offset-sm-1">
  <div class="row">
   {% for mob in mobiles%}
   <div class ="col-sm-4 test-center mb-4">
    <a href="{% url 'app:product-detail' mob.id %}" class="btn">
    <div class="item">
    <img src="{{mob.image.url}}" alt="any thing happend" height="300" class="">
    <div class="fw-bold">{{mob.title}}</div>
    <div class="fw-bold">Rs:{{mob.discount_price}}
    <small class="fw-light text-decoration-line-through">
    {{mob.selling_price}}</small></div>
    </div>
    </a>
   </div>
   {% endfor%}
  </div>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/orders.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %} Orders Placed{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
 <h3>Welcome  {{request.user}}</h3>
  <div class="col-sm-2 border-end">
   <ul class="list-unstyled">
    <li class="d-grid"><a href="{% url 'app:orders' %}" class="btn btn-primary">Orders</a></li>
   </ul>
  </div>
  <div class="col-sm-9 offset-sm-1">
  {% for op in orders %}
   <div class="row shadow-sm-mb-3">
    <div class="col-sm-2">
    <img src="{{op.product.image.url}}" alt="" srcset="" class="img-fluid" height="150" width="150">
     </div>
     <div class="col-sm-7">
     <p>Product:{{op.product.title}}</p>
     <p>Quantity:{{op.quantity}}</p>
     <p>Price:{{op.total_cost}}</p>
     <p>Status:{{op.status}}</p>
     <hr>
    </div>
   </div>

  {% endfor %}
 </div>
</div>
{% endblock main-content %}

app/templates/app/password_reset.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Reset Password{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row my-3">
 
  <div class="col-sm-6 offset-sm-3">
  <h3>Reset Password</h3>
   <form action="" method="post" novalidate class="shadow p-5">
    {% csrf_token %}
    {% for f in form %}
    <div class="form-group">
    {{f.label_tag}}{{f}}<small class="text-danger">{{f.errors|striptags}}</small><br>
    </div>
    {% endfor %}
     <input type="submit" class="btn btn-primary mt-4" value="save">
    <br>
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
    {% endfor %}
    {% endif %}
    </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/password_reset_complete.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}
 Password Reset Done {% endblock title %}
{% block main-content %}
<div class="container my-5">
<div class="row">
<h3>Password Reset Complete</h3>
<div class ="col-sm-2 border-end" >
<ul class="list-unstyled">
<li ckass ="d-grid"><a href = "{% url 'app:profile' %}" class="btn btn-primary">Change Password Done</a></li></ul>

</div>
<div class="col-sm-9 offset-sm-1 text-center">
<h3> Password Changed Successfully</h3>
<div><iframe src="https://giphy.com/embed/ibolLe3mOqHE3PQTtk" width="200" height="200" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>
</div>
</div>
{% endblock main-content %}

app/templates/app/password_reset_confirm.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Password Reset Confirm{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Password Reset Confirm</h3>
   <hr>
   <form action="" method="post" novalidate class="shadow p-5">
    {% csrf_token %}
    {% for f in form %}
    <div class="form-group">
    {{f.label_tag}}{{f}}<small class="text-danger">{{f.errors|striptags}}</small><br>
    </div>
    {% endfor %}
    
    <input type="submit" class="btn btn-primary mt-4" value="Submit">
    <br>
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
    {% endfor %}
    {% endif %}
    </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/productdetail.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Product Detail{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <div class="col-sm-6 text-center align-self-center">
   <img src="{{ product.image.url }}" alt="" class="img-fluid img-thumbnail">
  </div>
  <div class="col-sm-5 offset-sm-1">
   <h2>Product Title: {{product.title}}</h2>
   <hr>
    {{product.description}}
    <br>
   <h4>Rs. {{product.discount_price}} <small class="fw-light text-decoration-line-through">{{product.selling_price}}</small></h4> <br>
   {% if request.user.is_authenticated %}
   {% if item_already %}
   <a href="{%url 'app:showcart' %}" class="btn btn-warning shadow px-5 py-2 ">Go To Cart</a> 
   {% else %}
   <form action="/add-to-cart" class="d-inline">
   <input type="hidden" value={{product.id}} name="prod_id">
   <button type="submit" class="btn btn-primary shadow px-5 py-2">Add To Cart</button>
   </form>
   {% endif %}
{% endif %}
 {% if not request.user.is_authenticated %}
<form action="/add-to-cart" class="d-inline">
   <input type="hidden" value={{product.id}} name="prod_id">
   <button type="submit" class="btn btn-primary shadow px-5 py-2">Add To Cart</button>
   </form>
 {% endif %}
<a href="{% url 'app:checkout' %}" class="btn btn-danger shadow px-5 py-2 ms-4">Buy Now</a>
   <h5 class="mt-5">Available Offers</h5>
   <ul>
    <li>Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit</li>
    <li>Special Price Get extra ₹3000 off (price inclusive of discount)</li>
    <li>No cost EMI ₹1,667/month. Standard EMI also available</li>
    <li>Partner Offer ₹2000 Flipkart Gift Card on Every 1000th Transaction with a new Visa Debit/Credit Card</li>
   </ul>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/seller.html

<html>
<body>
This is sellers place
</body>
</html>